version: ~> 1.0

os: linux
dist: bionic
language: python

# FIXME: redis runs for all jobs. It's only needed for tests/examples
services:
  - redis

python:
  - &default_py 3.6
  - 3.7
  - 3.8
  # - pypy3
  - nightly

stages:
  - lint
  - test
  - examples

cache:
  pip: true

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=yes

install:
  - pip install .
  - pip install -r requirements/ci-test.txt

script:
  - make ci-test

after_script:
  - codecov -f coverage.xml

jobs:
  fast_finish: true
  allow_failures:
    - python: nightly

  include:
    - stage: lint
      name: black, flake8, isort, mypy
      python: *default_py
      install:
        - pip install -r requirements/lint.txt
      script:
        - make black-check
        - make flake8
        - make isort-check
        - make mypy

    - name: Dist
      python: *default_py
      install:
        - pip install -r requirements/wheels.txt
      script:
        - make dist

    - stage: test
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
        - choco install make
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

    - python: pypy3
      os: linux
      dist: xenial  # pypy 7-3.6 is not yet supported on bionic in travis

    - stage: examples
      python: *default_py
      install:
        - pip install .
      script:
        - make examples

deploy:
  edge: true

  provider: pypi
  username: Fogapod
  twine_check: false
  distributions: "sdist bdist_wheel"
  on:
    tags: true
